#!/bin/bash

echo "Enter input filePath"
read input
echo ________________________________________
echo "[vanilla file]:"
echo " "
cat $input
echo ________________________________________
echo "[reworked file]:"
g++ -std=c++11 Source/main.cpp && ./a.out <<< $input
echo " "
cat "output.txt"
echo ________________________________________
rm output.txt


